### ISSUE TITLE
It seems input node feature's dimension has not aligned with GMT?

### ISSUE THREAD

**Issue by yunchong-song** [Wu-Junran/SEP#3]
Hi, in your paper you said the input node feature for social datasets are one-hot encodings of node degrees:

> Thus, the initial node features of the HRN inputs are set to one-hot encodings of the node degrees for social networks and a combination of the one-hot encodings of the degrees and categorical labels for bioinformatic graphs.

And [GMT](https://github.com/JinheonBaek/GMT) also follow the same setting as yours for social datasets:

> we use the one-hot encoding of their atom types as initial node features in the bio-chemical datasets, and the one-hot encoding of node degrees as initial node features in the social datasets.

However, when I run GMT and SEP, I found even for social datasets, the input node feature's dimension is not the same:
<img width="996" alt="image" src="https://user-images.githubusercontent.com/57980447/189932727-c2fb57da-b91c-45d4-aa16-434b43506b34.png">
<img width="660" alt="image" src="https://user-images.githubusercontent.com/57980447/189932882-67da020d-3116-4765-b996-44fd59dddd8c.png">

GMT use the [OneHotDegree](https://pytorch-geometric.readthedocs.io/en/latest/modules/transforms.html#torch_geometric.transforms.OneHotDegree) function provided by [PyG](https://pytorch-geometric.readthedocs.io/en/latest/modules/transforms.html#torch_geometric.transforms.OneHotDegree) to implement the transformation for raw data (see https://github.com/JinheonBaek/GMT/blob/main/utils/data.py), which should be treat as a standard implementation, and you mentiond you follow the scripts of GMT in your paper:

> Because GMT is the most recent work that replicates these popular pooling approaches in previous studies, and we implement SEP-G based on the code of GMT

I'm confused why the dimension would be different, it is important to know how you process the raw data to node features, can you help me?

**Comment by Wu-Junran** [comment]
Since you have run the code of SEP and GMT, you tell us why.

Of course, I know the reason, but I prefer you find the code difference for degree one-hot embedding by yourself.

**Comment by yunchong-song** [comment]
> Since you have run the code of SEP and GMT, you tell us why.
> 
> Of course, I know the reason, but I prefer you find the code difference for degree one-hot embedding by yourself.

I guess when encoding the degrees, you've skiped the degree that doesn't exactly exist in dataset, am I right?

**Comment by Wu-Junran** [comment]
Genius, this is the exact reason. 

Now, in your view, whether the two embedding methods make any difference in model performance? In my view, they are the same.

**Comment by yunchong-song** [comment]
> Genius, this is the exact reason.
> 
> Now, in your view, whether the two embedding methods make any difference in model performance? In my view, they are the same.

Yes, basically the same, your implementation might save some computation budget for empty column in standard node feature matrix caused by non-exist degrees.
